import { Prisma } from '@client-online';

export class Restaurant implements Prisma.RestaurantUncheckedCreateInput {
  id?: number;
  RestaurantRevenue?: Prisma.RestaurantRevenueUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByDrinkCategory?: Prisma.RestaurantRevenueByDrinkCategoryUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByDrinkCategoryPercent?: Prisma.RestaurantRevenueByDrinkCategoryPercentUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByFoodCategory?: Prisma.RestaurantRevenueByFoodCategoryUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByFoodCategoryPercent?: Prisma.RestaurantRevenueByFoodCategoryPercentUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByGroupByPeriod?: Prisma.RestaurantRevenueByGroupByPeriodUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByOthersCategory?: Prisma.RestaurantRevenueByOthersCategoryUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByOthersCategoryPercent?: Prisma.RestaurantRevenueByOthersCategoryPercentUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByPeriod?: Prisma.RestaurantRevenueByPeriodUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantRevenueByPeriodPercent?: Prisma.RestaurantRevenueByPeriodPercentUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantSales?: Prisma.RestaurantSalesUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantSalesByDrinkCategory?: Prisma.RestaurantSalesByDrinkCategoryUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantSalesByFoodCategory?: Prisma.RestaurantSalesByFoodCategoryUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantSalesByOthersCategory?: Prisma.RestaurantSalesByOthersCategoryUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantSalesRanking?: Prisma.RestaurantSalesRankingUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantTicketAverage?: Prisma.RestaurantTicketAverageUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantTicketAverageByPeriod?: Prisma.RestaurantTicketAverageByPeriodUncheckedCreateNestedManyWithoutRestaurantInput;
  RestaurantTicketAverageByTotalRentals?: Prisma.RestaurantTicketAverageByTotalRentalsUncheckedCreateNestedManyWithoutRestaurantInput;
  companyId: number;
}
